# Generated by Django 3.1.4 on 2021-05-10 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Choose_Coin', models.CharField(blank=True, max_length=265, null=True)),
                ('Alert_me_on', models.CharField(blank=True, max_length=265, null=True)),
                ('When_price_of_coin', models.CharField(blank=True, max_length=265, null=True)),
                ('Goes', models.CharField(blank=True, max_length=265, null=True)),
                ('by', models.IntegerField(null=True)),
                ('COLLDOWN', models.DateTimeField(default=django.utils.timezone.now)),
                ('Add_a_note', models.CharField(blank=True, max_length=265, null=True)),
                ('by_currency', models.CharField(blank=True, max_length=265, null=True)),
            ],
            options={
                'db_table': 'Price',
            },
        ),
    ]
