# Generated by Django 3.1.4 on 2021-05-11 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_coin', models.CharField(blank=True, max_length=265, null=True)),
                ('alert_me_on', models.CharField(blank=True, max_length=265, null=True)),
                ('when_price_of_coin', models.CharField(blank=True, max_length=265, null=True)),
                ('goes', models.CharField(blank=True, max_length=265, null=True)),
                ('by', models.IntegerField(blank=True, null=True)),
                ('colldown', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('add_a_note', models.CharField(blank=True, max_length=265, null=True)),
                ('by_currency', models.CharField(blank=True, max_length=265, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Price',
            },
        ),
    ]
