# Generated by Django 3.1.4 on 2021-05-10 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='COLLDOWN',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
